### ISSUE TITLE
Any plan to add write capability?

### ISSUE THREAD

**Issue by vampywiz17** [beep-projects/SystaPi#2]
Hello there!

It seems a great project!

My question is that any plan to add write config? (like change pre-set programs)?

**Comment by beep-projects** [comment]
I am currently looking into that, but I have not found any good protocol description except this https://community.openhab.org/uploads/short-url/d9EE8RfvameaneEkC6oZqHlrDdM.txt
So I guess it will take a while

**Comment by vampywiz17** [comment]
I see, thanks the answer and good work! I hope it will work!
