### ISSUE TITLE
seem not to work anymore. It installs OS but i do not find SystaPi-2.0

### ISSUE THREAD

**Issue by beep-projects** [beep-projects/SystaPi#9]
seem not to work anymore. It installs OS but i do not find SystaPi-2.0
I am on Ubuntu , is there a Chance to get an Update?
I tried it on Windows, no success .
SW Version: Software V2.16 9.03.21 and RPI3
Appriciation

_Originally posted by @errut in https://github.com/beep-projects/SystaPi/discussions/4#discussioncomment-2644636_

**Comment by errut** [comment]
ok, one easy one: disk since i use usb i had to change disk in the script. Installation was successfull.
Question: I am on 192.168.178.x, do i understand this correctly : in the Script the ip must in a different network,  so i change to 192.168.178.1.
rpi was booting into the commandline of the rpi

**Comment by beep-projects** [comment]
You can pass the path for the sd card in your card reader to the script, so you don't have to change the script.
e.g. install_systapi.sh /dev/mmcblk0 

By default, the WiFi interface is used to connect to your WiFi networt using DHCP (assuming that you configured the ssid and passphrase in firstrun.sh).
The Ethernet interface is used to connect the Raspberry Pi to your SystaComfort.
By default the 192.168.1.1 is used for this on the SystaPi. This will cause networking issues, if you use this IP range for your local WiFi. But since you use 192.168.178.x (I assume the netmask is set accordingly) you should not have any conflict and you can go with the default configuration. 
If you use 192.168.178.1 on the Ethernet interface of the pi and 192.168.178.x on your local WiFi, you should create a network conflict and SystaPi will not receive the data.

If your pi is booting and connecting to your WiFi, you should be able to get the setup logs from the SystaPi by running the following command on the command line of your Ubuntu computer
`scp beep@systapi:/boot/*.log .`
and get the server logs via
`ssh beep@systapi "journalctl -u SystaRESTServer.service" > SystaPi_journalctl.log`

**Comment by beep-projects** [comment]
@errut is it now working for you?

**Comment by errut** [comment]
No, not yet.
I change to SD-Card, so I didn`t have the problem with the disk. It is booting , it stops booting: I can see the thee BT- and the sound-icon, but nothing else on the desktop.I tried wlan and Lan aswell.
Presently i am using Systaweb for one year, but i want systapi.
